#!/bin/bash

set -o errexit
set -o pipefail
set -o nounset

python /app/manage.py makemigrations
python /app/manage.py migrate
python /app/manage.py collectstatic --noinput
# exec python manage.py runserver_plus 0.0.0.0:5000
exec /opt/venv/bin/gunicorn --config /gunicorn-cfg.py config.wsgi --chdir=/app
