# Generated by Django 4.2.14 on 2024-07-21 13:46

import django.core.validators
from django.db import migrations, models
import rhixe_scans.users.models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="images",
            field=models.ImageField(
                default="/images/user.png",
                upload_to=rhixe_scans.users.models.user_image_location,
                validators=[
                    django.core.validators.FileExtensionValidator(
                        [
                            "ico",
                            "jpg",
                            "svg",
                            "jpeg",
                            "png",
                            "gif",
                            "bmp",
                            "webp",
                            "tiff",
                        ]
                    )
                ],
                verbose_name="Images",
            ),
        ),
    ]
