# Generated by Django 5.0.7 on 2024-07-14 20:25

import core.models
import django.core.validators
import django.db.models.deletion
import django.db.models.functions.text
import django.utils.timezone
import django_ckeditor_5.fields
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Artist",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(max_length=500, unique=True, verbose_name="Name"),
                ),
            ],
            options={
                "verbose_name_plural": "Artists",
            },
        ),
        migrations.CreateModel(
            name="Author",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(max_length=500, unique=True, verbose_name="Name"),
                ),
            ],
            options={
                "verbose_name_plural": "Authors",
            },
        ),
        migrations.CreateModel(
            name="Category",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(max_length=1020, unique=True, verbose_name="Name"),
                ),
            ],
            options={
                "verbose_name_plural": "Categories",
            },
        ),
        migrations.CreateModel(
            name="Chapter",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=50000, verbose_name="Name")),
                (
                    "slug",
                    models.SlugField(
                        default="", max_length=50000, unique=True, verbose_name="Slug"
                    ),
                ),
                ("crawled", models.DateField(default="", verbose_name="Downloaded")),
                (
                    "url",
                    models.URLField(
                        blank=True, max_length=50000, null=True, verbose_name="Url"
                    ),
                ),
                (
                    "numPages",
                    models.PositiveSmallIntegerField(
                        default=0, verbose_name="Total Pages"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Updated"),
                ),
                (
                    "created_at",
                    models.DateField(auto_now_add=True, verbose_name="Published"),
                ),
            ],
            options={
                "verbose_name_plural": "Chapters",
                "ordering": [django.db.models.functions.text.Upper("name")],
                "get_latest_by": "-updated_at",
            },
        ),
        migrations.CreateModel(
            name="Comment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(max_length=50, unique=True, verbose_name="Name"),
                ),
                ("body", django_ckeditor_5.fields.CKEditor5Field(verbose_name="Body")),
                ("publish", models.DateTimeField(default=django.utils.timezone.now)),
                ("lft", models.PositiveIntegerField(editable=False)),
                ("rght", models.PositiveIntegerField(editable=False)),
                ("tree_id", models.PositiveIntegerField(db_index=True, editable=False)),
                ("level", models.PositiveIntegerField(editable=False)),
            ],
            options={
                "verbose_name_plural": "Comments",
            },
        ),
        migrations.CreateModel(
            name="Genre",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(max_length=100, unique=True, verbose_name="Name"),
                ),
            ],
            options={
                "verbose_name_plural": "Genres",
            },
        ),
        migrations.CreateModel(
            name="Panel",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "images",
                    models.ImageField(
                        blank=True,
                        default="/images/placeholder.png",
                        max_length=40000,
                        upload_to=core.models.panel_location,
                        validators=[
                            django.core.validators.FileExtensionValidator(
                                [
                                    "ico",
                                    "png",
                                    "jpg",
                                    "svg",
                                    "jpeg",
                                    "gif",
                                    "webp",
                                    "ttf",
                                    "eot",
                                    "woff",
                                    "woff2",
                                ]
                            )
                        ],
                        verbose_name="Images",
                    ),
                ),
                ("image_urls", models.URLField(max_length=40000)),
            ],
            options={
                "verbose_name_plural": "Panels",
            },
        ),
        migrations.CreateModel(
            name="UserComics",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("order", models.PositiveSmallIntegerField()),
            ],
            options={
                "ordering": ["order"],
            },
        ),
        migrations.CreateModel(
            name="Vote",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("vote", models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name="Comic",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        max_length=50000, unique=True, verbose_name="Title"
                    ),
                ),
                (
                    "slug",
                    models.SlugField(
                        blank=True,
                        default="",
                        max_length=50000,
                        unique=True,
                        verbose_name="Slug",
                    ),
                ),
                (
                    "images",
                    models.ImageField(
                        blank=True,
                        default="/images/placeholder.png",
                        max_length=40000,
                        upload_to=core.models.comic_location,
                        validators=[
                            django.core.validators.FileExtensionValidator(
                                [
                                    "ico",
                                    "png",
                                    "jpg",
                                    "svg",
                                    "jpeg",
                                    "gif",
                                    "webp",
                                    "ttf",
                                    "eot",
                                    "woff",
                                    "woff2",
                                ]
                            )
                        ],
                        verbose_name="Images",
                    ),
                ),
                (
                    "image_urls",
                    models.URLField(blank=True, max_length=40000, null=True),
                ),
                (
                    "description",
                    models.TextField(blank=True, null=True, verbose_name="Description"),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("Completed", "completed"),
                            ("Ongoing", "ongoing"),
                            ("Dropped", "dropped"),
                            ("Coming_Soon", "coming_soon"),
                            ("Hiatus", "hiatus"),
                        ],
                        max_length=150,
                        verbose_name="Status",
                    ),
                ),
                ("rating", models.FloatField(verbose_name="Rating")),
                (
                    "alternativetitle",
                    models.CharField(
                        blank=True,
                        max_length=50000,
                        null=True,
                        verbose_name="Alternative Title",
                    ),
                ),
                (
                    "released",
                    models.CharField(
                        blank=True, max_length=50000, null=True, verbose_name="Released"
                    ),
                ),
                (
                    "serialization",
                    models.CharField(
                        blank=True,
                        max_length=50000,
                        null=True,
                        verbose_name="Serialization",
                    ),
                ),
                (
                    "postedby",
                    models.CharField(
                        blank=True,
                        max_length=50000,
                        null=True,
                        verbose_name="Posted by",
                    ),
                ),
                (
                    "numChapters",
                    models.PositiveSmallIntegerField(
                        default=0, verbose_name="Total Chapters"
                    ),
                ),
                (
                    "url",
                    models.URLField(
                        blank=True, max_length=50000, null=True, verbose_name="Url"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        default=django.utils.timezone.now, verbose_name="Updated"
                    ),
                ),
                ("crawled", models.DateField(verbose_name="Downloaded")),
                ("created_at", models.DateField(verbose_name="Published")),
                ("like_count", models.BigIntegerField(default="0")),
                ("thumbsup", models.IntegerField(default="0")),
                ("thumbsdown", models.IntegerField(default="0")),
                (
                    "artist",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="comic_artist",
                        to="core.artist",
                    ),
                ),
                (
                    "author",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="comic_author",
                        to="core.author",
                    ),
                ),
                (
                    "category",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="comic_category",
                        to="core.category",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Comics",
                "ordering": [
                    "-updated_at",
                    django.db.models.functions.text.Lower("title"),
                ],
                "get_latest_by": "updated_at",
            },
        ),
    ]
