# Generated by Django 5.0.7 on 2024-07-15 05:31

import core.models
import django.core.validators
import django_ckeditor_5.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0002_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="comic",
            name="images",
            field=models.ImageField(
                blank=True,
                default="/images/placeholder.png",
                max_length=40000,
                upload_to=core.models.comic_location,
                validators=[
                    django.core.validators.FileExtensionValidator(
                        [
                            "ico",
                            "jpg",
                            "svg",
                            "jpeg",
                            "png",
                            "gif",
                            "bmp",
                            "webp",
                            "tiff",
                        ]
                    )
                ],
                verbose_name="Images",
            ),
        ),
        migrations.AlterField(
            model_name="comment",
            name="body",
            field=django_ckeditor_5.fields.CKEditor5Field(
                blank=True, null=True, verbose_name="Body"
            ),
        ),
        migrations.AlterField(
            model_name="panel",
            name="images",
            field=models.ImageField(
                blank=True,
                default="/images/placeholder.png",
                max_length=40000,
                upload_to=core.models.panel_location,
                validators=[
                    django.core.validators.FileExtensionValidator(
                        [
                            "ico",
                            "jpg",
                            "svg",
                            "jpeg",
                            "png",
                            "gif",
                            "bmp",
                            "webp",
                            "tiff",
                        ]
                    )
                ],
                verbose_name="Images",
            ),
        ),
    ]
