services:
  docs:
    image: rhixe/rhixe_scans:docs
    container_name: docs
    build:
      context: .
      dockerfile: ./compose/local/docs/Dockerfile
    env_file:
      - ./.envs/.local/.django
    volumes:
      - ./docs:/docs:z
      - ./config:/app/config:z
      - ./rhixe_scans:/app/rhixe_scans:z
    ports:
      - "9000:9000"
    command: /start-docs
