#!/bin/bash

set -o errexit
set -o pipefail
set -o nounset

# python manage.py makemigrations
python manage.py migrate
python manage.py collectstatic --noinput
# exec python manage.py runserver_plus 0.0.0.0:5000
exec gunicorn --config /home/bot/gunicorn-cfg.py config.wsgi --chdir=/home/bot/app
